version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass@word123"
      ACCEPT_EULA: "Y"
    networks:
      - shopping-website-api

  backend:
    image: ${DOCKER_REGISTRY-}shopping-website-server
    container_name: shopping-website-server
    build:
      context: ./ShoppingWebsite.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "7259:443"
    depends_on:
      - db
    networks:
      - shopping-website-api

volumes:
  db-data:
networks:
  shopping-website-api:
    driver: bridge   
